name: Crypto Data Updater

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  update_crypto_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: pip install -r requirements.txt

    - name: Check Environment Variables
      run: |
        if [[ -z "$GCP_SERVICE_ACCOUNT" ]]; then
          echo "❌ ERROR: GCP_SERVICE_ACCOUNT is missing!"
          exit 1
        else
          echo "✅ GCP_SERVICE_ACCOUNT is set."
          echo $GCP_SERVICE_ACCOUNT | base64 --decode | jq .
        fi
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Run Crypto Data Script
      env:
        GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      run: python script.py
